version: '3'
services:
  nuxtjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: asana-clone
    environment:
      NODE_ENV: development
    volumes:
       - ./:/usr/app
    user: node
    entrypoint: /bin/sh '/usr/app/entrypoint.sh'
